name: Release

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and create archive
        run: ./tools/release.ps1
        shell: pwsh
      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./blessing-skin-server-*
